name: testflows

on:
  workflow_dispatch:
  # schedule:
    # - cron: 0 18 * * *

env:
  CACHE_TOOLCHAIN: true
  UPLOAD_BIN_DIR: false
  FIRMWARE_RELEASE: true
  FIRMWARE_TAG: Rockchip
  TZ: Asia/Shanghai

jobs:
  Build:
    runs-on: ubuntu-22.04

    steps:
    - name: Check Server Performance
      run: |
        echo "警告⚠"
        echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
        echo -e "已知CPU型号(降序): 7763，8370C，8272CL，8171M，E5-2673\n"
        echo "--------------------------CPU信息--------------------------"
        echo "CPU物理数量: $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
        echo "CPU核心数量: $(nproc)"
        echo -e "CPU型号信息:$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
        echo "--------------------------内存信息--------------------------"
        echo "已安装内存详细信息:"
        echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
        echo "--------------------------硬盘信息--------------------------"
        echo "硬盘数量: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT
        
    - name: 检查项目分支(checkout)
      uses: actions/checkout@main

    - name: 下载固件源码(Clone Source Code)
      run: |
        df -hT $GITHUB_WORKSPACE
        ls -al
        # cp $GITHUB_WORKSPACE/ipq6000-re-ss-01.dts workdir/
        # cd workdir
        # cat ipq6000-re-ss-01.dts 
        # sed -i "s/\(model *= *\"\)[^\"]*\(\"\)/\1PHilips LY-1800\2/" "ipq6000-re-ss-01.dts"
        # cat ipq6000-re-ss-01.dts
        chmod +x $GITHUB_WORKSPACE/Scripts/Packages.sh
        $GITHUB_WORKSPACE/Scripts/Packages.sh
        ls -al
        echo "下面显示argon的目录"
        cd luci-theme-argon
        ls -al
        echo "下面显示lucky的目录"
        cd ../luci-app-lucky
        ls -al
        echo "下面显示small的目录"
        cd ../small
        ls -al